NexusCorpFilmReviews/NexusCorpFilmReviews/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NexusCorpFilmReviews.Models;

namespace NexusCorpFilmReviews.Controllers
{
    public class ActorsController : Controller
    {
        private FilmContext db = new FilmContext();

        // GET: Actors
        public ActionResult Index()
        {
            return View(db.Actors.ToList());
        }

        // GET: Actors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actor actor = db.Actors.Find(id);
            if (actor == null)
            {
                return HttpNotFound();
            }
            return View(actor);
        }

        // GET: Actors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ActorId,ActorFirstName,ActorLastName,ActorDOB,ActorAge,ActorGender")] Actor actor)
        {
            if (ModelState.IsValid)
            {
                db.Actors.Add(actor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(actor);
        }

        // GET: Actors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actor actor = db.Actors.Find(id);
            if (actor == null)
            {
                return HttpNotFound();
            }
            return View(actor);
        }

        // POST: Actors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ActorId,ActorFirstName,ActorLastName,ActorDOB,ActorAge,ActorGender")] Actor actor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(actor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(actor);
        }

        // GET: Actors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actor actor = db.Actors.Find(id);
            if (actor == null)
            {
                return HttpNotFound();
            }
            return View(actor);
        }

        // POST: Actors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Actor actor = db.Actors.Find(id);
            db.Actors.Remove(actor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NexusCorpFilmReviews/NexusCorpFilmReviews/Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using NexusCorpFilmReviews.Models;

//Namespace for the film controller class
namespace NexusCorpFilmReviews.Controllers
{
    //public class body for the film controller class. All the code for this controller class needs to be inside this public body fucntion
    public class FilmsController : Controller
    {
        //Create a private variable called db connecting it to the film context
        private FilmContext db = new FilmContext();

        // public action result function for the index, which returns a view of all the connected keys to the film class 
        public ActionResult Index()
        {
            //Using ViewBag, retrieve the username that matches the username stored in the database
            ViewBag.UserName = User.Identity.GetUserId();

            var films = db.Films.Include(f => f.Actor).Include(f => f.Director).Include(f => f.Genre);
            return View(films.ToList());
        }

        // GET: Films/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = db.Films.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        // GET: Films/Create
        public ActionResult Create()
        {
            ViewBag.ActorId = new SelectList(db.Actors, "ActorId", "ActorFirstName");
            ViewBag.DirectorId = new SelectList(db.Directors, "DirectorId", "DirectorFirstName");
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "GenreType");
            return View();
        }

        // POST: Films/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FilmId,GenreId,ActorId,DirectorId,FilmName,FilmDescription,ReleaseDate,Rating,UserName,FilmImage")] Film film)
        {
            if (ModelState.IsValid)
            {
                //getting the user name from the data base and storing it in the UserName Variable
                film.UserName = User.Identity.GetUserId();
                db.Films.Add(film);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ActorId = new SelectList(db.Actors, "ActorId", "ActorFirstName", film.ActorId);
            ViewBag.DirectorId = new SelectList(db.Directors, "DirectorId", "DirectorFirstName", film.DirectorId);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "GenreType", film.GenreId);
            return View(film);
        }

        // GET: Films/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = db.Films.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            ViewBag.ActorId = new SelectList(db.Actors, "ActorId", "ActorFirstName", film.ActorId);
            ViewBag.DirectorId = new SelectList(db.Directors, "DirectorId", "DirectorFirstName", film.DirectorId);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "GenreType", film.GenreId);
            return View(film);
        }

        // POST: Films/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FilmId,GenreId,ActorId,DirectorId,FilmName,FilmDescription,ReleaseDate,Rating,UserName,FilmImage")] Film film)
        {
            if (ModelState.IsValid)
            {
                //getting the user name from the data base and storing it in the UserName Variable
                film.UserName = User.Identity.GetUserId();
                db.Entry(film).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ActorId = new SelectList(db.Actors, "ActorId", "ActorFirstName", film.ActorId);
            ViewBag.DirectorId = new SelectList(db.Directors, "DirectorId", "DirectorFirstName", film.DirectorId);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "GenreType", film.GenreId);
            return View(film);
        }

        // GET: Films/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = db.Films.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        // POST: Films/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Film film = db.Films.Find(id);
            db.Films.Remove(film);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Protected ovveride void function for removing the film from the database  
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NexusCorpFilmReviews/NexusCorpFilmReviews/Controllers/GossipsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NexusCorpFilmReviews.Models;

namespace NexusCorpFilmReviews.Controllers
{
    public class GossipsController : Controller
    {
        private FilmContext db = new FilmContext();

        // GET: Gossips
        public ActionResult Index()
        {
            return View(db.Gossips.ToList());
        }

        // GET: Gossips/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gossip gossip = db.Gossips.Find(id);
            if (gossip == null)
            {
                return HttpNotFound();
            }
            return View(gossip);
        }

        // GET: Gossips/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Gossips/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GossipId,GossipContent,GossipContentDateAdded,UserName")] Gossip gossip)
        {
            if (ModelState.IsValid)
            {
                db.Gossips.Add(gossip);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(gossip);
        }

        // GET: Gossips/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gossip gossip = db.Gossips.Find(id);
            if (gossip == null)
            {
                return HttpNotFound();
            }
            return View(gossip);
        }

        // POST: Gossips/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GossipId,GossipContent,GossipContentDateAdded,UserName")] Gossip gossip)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gossip).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gossip);
        }

        // GET: Gossips/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gossip gossip = db.Gossips.Find(id);
            if (gossip == null)
            {
                return HttpNotFound();
            }
            return View(gossip);
        }

        // POST: Gossips/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Gossip gossip = db.Gossips.Find(id);
            db.Gossips.Remove(gossip);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NexusCorpFilmReviews/NexusCorpFilmReviews/Views/Shared/_ActorLayout.cshtml
<!DOCTYPE html>
<br />
<br />
<br>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="background: #ffffff">
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-primary">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"></button>
            @Html.ActionLink("Nexus Film Reviews", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <div class="navbar-collapse collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav  mr-auto">
                    <li class="nav-item">@Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("About", "About", "Home", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Film", "Index", "Films", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Actor", "Index", "Actors", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Director", "Index", "Directors", null, new { @class = "nav-link" })</li>
                </ul>
                @Html.Partial("_LoginPartial")

            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

NexusCorpFilmReviews/NexusCorpFilmReviews/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<br />
<br />
<br>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Nexus Film Reviews</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="background: #ffffff">
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-primary">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"></button>
            @Html.ActionLink("Nexus Film Reviews", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <div class="navbar-collapse collapse" id="navbarSupportedContent">
               
                <ul class="nav navbar-nav  mr-auto">
                    <li class="nav-item"><p style="font-size:16px">@Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })</p></li>
                    <li class="nav-item"><p style="font-size:16px">@Html.ActionLink("About", "About", "Home", null, new { @class = "nav-link" })</p></li>
                    <li class="nav-item"><p style="font-size:16px">@Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "nav-link" })</p></li>
                    <li class="nav-item"><p style="font-size:16px">@Html.ActionLink("Film", "Index", "Films", null, new { @class = "nav-link" })</p></li>
                    <li class="nav-item"><p style="font-size:16px">@Html.ActionLink("Actor", "Index", "Actors", null, new { @class = "nav-link" })</p></li>
                    <li class="nav-item"><p style="font-size:16px">@Html.ActionLink("Director", "Index", "Directors", null, new { @class = "nav-link" })</p></li>
                    <li class="nav-item"><p style="font-size:16px">@Html.ActionLink("Gossip", "Index", "Gossips", null, new { @class = "nav-link" })</p></li>
                    <li class="nav-item"><p style="font-size:16px">@Html.ActionLink("Register", "Register", "Account", null, new { @class = "nav-link" })</p></li>
                    <li class="nav-item"><p style="font-size:16px">@Html.ActionLink("Log in", "Login", "Account", null, new { @class = "nav-link" })</p></li>

                </ul>
                @Html.Partial("_LoginPartial")
                
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Nexus Corporation</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>